version: '3.4'
services:
  push-tf-secondary-2:
    container_name: "push-tf-secondary-2"
    hostname: "push-tf-secondary-2"
    tty: true
    image: eismcc/push-tensorflow-gpu:latest
    expose:
      - '10002'
      - '11002'
      - '50002'
    env_file:
      - ./envs/push.env
    volumes:
      - ./conf/push.bootstrap.conf.yml:/opt/push/conf/push.conf.yml
      - $PUSH_HOME:/scm/push
    command: ["python","/scm/push/push/push_server.py /opt/push/conf/push.conf.yml"]
    network_mode: host
